function(is_musl_c result_a)
    block(SCOPE_FOR VARIABLES)
        set(out_string "")
        execute_process(COMMAND ldd /bin/ls COMMAND grep "musl" COMMAND head -1 OUTPUT_VARIABLE out_string)
        if("${out_string}" STREQUAL "")
            set(${result_a} FALSE)
            return(PROPAGATE ${result_a})
        endif()
        set(${result_a} TRUE)
        return(PROPAGATE ${result_a})
    endblock()
endfunction()